### PR TITLE
Added support for KPBS, Luciole, Octosat, Bumblebee, Alcor, and MK2X.

### PR DESCRIPTION
**Pull request by jthero3**

### CODE REVIEW

**Comment by Adventurer13** [comment]
@jthero3
[A KPBS config](https://github.com/Sheepdog2142/VABOrganizer-Sheepdog/blob/v1.3/GameData/VABOrganizer-Sheepdog/KPBS/KPBS_VABO.cfg) currently exists on the v1.3 branch. Does that satisfy instead or are there suggestions/problems with the current implementation?

**Comment by jthero3** [comment]
Yeah, that one works! I didn't notice it while I was doing my initial checks.

**Comment by Adventurer13** [comment]
All good, just wanted to solve that potential conflict.

**Comment by Sheepdog2142** [comment]
This still need to be merged?

**Comment by Adventurer13** [comment]
I would say so. Affects support for 8 mods (unless already supported) and a 2nd pass on the Planetside Exploration support. Is this correct, @jthero3?

- [ALCOR](https://github.com/FirstPersonKSP/KSP-ALCOR)
- [Bumblebee](https://github.com/Rodg88/BumbleBee)
- [Coriolis Space Systems](https://spacedock.info/mod/2706/Coriolis%20Space%20Systems)
- [DaMichel's CargoBays](https://github.com/zer0Kerbal/CargoBays)
- [HullcamVDSContinued](https://github.com/linuxgurugamer/HullcamVDSContinued)
- [Luciole](https://github.com/AstroWell/Luciole)
- [Mk2Expansion](https://github.com/SuicidalInsanity/Mk2Expansion)
- [NSS/OctoSat-SOAR S3-A300t](https://github.com/linuxgurugamer/NSS)
- [Planetside Exploration Technologies](https://github.com/benjee10/Benjee10_MMSEV)

---
Side note, the title should probably be updated.

**Comment by jthero3** [comment]
Yeah, that's correct.

**Pull request merged**
